# Generated by Django 5.1.7 on 2025-03-31 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_monthwise_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
