# Generated by Django 5.1.7 on 2025-03-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_expense_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthwise',
            name='per_minute_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
