# Generated by Django 5.1.7 on 2025-03-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_monthwise_per_minute_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthwise',
            name='per_day_salary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthwise',
            name='per_minute_salary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
