# Generated by Django 5.1.7 on 2025-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_monthwise_per_day_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='time_value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
