# Generated by Django 5.1.7 on 2025-03-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_expense_time_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time_value_in_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
